### ISSUE TITLE
error happen when running pos install

### ISSUE THREAD

**Issue by cfdtlee** [CanvasPod/Canvas#44]
» pod install
Updating local specs repositories

CocoaPods 1.0.0.beta.6 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
### Command

```
/Users/eric/.rvm/gems/ruby-2.3.0/bin/pod install
```
### Report
- What did you do?
  I run command `pod install`
- What did you expect to happen?
  Canvas is supposed to install.
- What happened instead?
  but an error occurs.
### Stack

```
   CocoaPods : 0.39.0
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.2 (15C50)
       Xcode : 7.1.1 (7B1005)
         Git : git version 2.4.9 (Apple Git-60)
Ruby lib dir : /Users/eric/.rvm/rubies/ruby-2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 92aabb977e468f5c6955406c79c520e91f013e63
```
### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-search  : 0.1.0
cocoapods-stats   : 0.6.2
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.5.1
```
### Podfile

``` ruby
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'
pod 'Canvas', '~> 0.1.2'
```
### Error

```
NoMethodError - undefined method `to_ary' for #<Pod::Specification name="Canvas">
Did you mean?  to_query
/Users/eric/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver/lazy_specification.rb:14:in `method_missing'
/Users/eric/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:64:in `flatten'
/Users/eric/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:64:in `block in resolve'
/Users/eric/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:63:in `tap'
/Users/eric/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:63:in `resolve'
/Users/eric/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:539:in `block in resolve_dependencies'
/Users/eric/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Users/eric/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:537:in `resolve_dependencies'
/Users/eric/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:70:in `analyze'
/Users/eric/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:213:in `analyze'
/Users/eric/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:136:in `block in resolve_dependencies'
/Users/eric/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Users/eric/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:135:in `resolve_dependencies'
/Users/eric/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:105:in `install!'
/Users/eric/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/eric/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:101:in `run'
/Users/eric/.rvm/gems/ruby-2.3.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/eric/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Users/eric/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/Users/eric/.rvm/gems/ruby-2.3.0/bin/pod:23:in `load'
/Users/eric/.rvm/gems/ruby-2.3.0/bin/pod:23:in `<main>'
/Users/eric/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/Users/eric/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by wilddylan** [comment]
try： sudo gem uninstall cocoapods
sudo gem install cocoapods

**Comment by cfdtlee** [comment]
Thank you. I tried, but still the same problem.

**Comment by wilddylan** [comment]
it's noamal when i use.
1. cd the xcode project and do `pod init`
2. in your main target 
   <img width="509" alt="2016-04-10 9 09 44" src="https://cloud.githubusercontent.com/assets/2519544/14407448/001d49de-fefc-11e5-900f-a319462b139c.png">
3. pod install --no-repo-update
   <img width="568" alt="2016-04-10 9 10 27" src="https://cloud.githubusercontent.com/assets/2519544/14407457/1abd49ce-fefc-11e5-8672-438e88847f3e.png">
4. your error, ... the `cocoapods` command throw an exception when query the `canvas`, missing the function. but we don't know `cocoapods` code so if you re install this command and redo it but can'f fix your bug... you should create new issue in [cocoapods](https://github.com/CocoaPods/CocoaPods)

**Comment by cfdtlee** [comment]
Ok, thanks!
